ignored = ["github.com/onsi/ginkgo", "github.com/onsi/gomega"]

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/graph-gophers/graphql-go"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"

[[constraint]]
  name = "gopkg.in/gormigrate.v1"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true